/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visao;

import modelos.Proprietario;
import modelos.Telefone;
import java.io.File;
import javax.swing.JFileChooser;
import controle.ProprietarioControle;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import modelos.IProprietarioCRUD;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pcgamergab
 */
public class TelaDeCadastroDeProprietarios extends javax.swing.JInternalFrame {

    IProprietarioCRUD proprietarioControle = null;
    String caminho = "";
    DefaultTableModel model;

    public TelaDeCadastroDeProprietarios() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        model = (DefaultTableModel) jTableSaida.getModel();

        proprietarioControle = new ProprietarioControle();
        mostrarDados();

    }

    private void mostrarDados() {
        try {
            ArrayList<Proprietario> listaDeProprietarios = null;
            Telefone fone = null;
            listaDeProprietarios = proprietarioControle.ObterListagemDeContatos();
            DefaultTableModel model = (DefaultTableModel) jTableSaida.getModel();
            model.setNumRows(0);
            if (listaDeProprietarios.isEmpty()) {
                return;
            }
            for (int pos = 0; pos < listaDeProprietarios.size(); pos++) {
                Proprietario listaProprietarios = listaDeProprietarios.get(pos);

                fone = listaProprietarios.getFone();

                String[] linha = new String[7];

                linha[0] = listaProprietarios.getCpf();
                linha[1] = listaProprietarios.getNomecompleto();
                linha[2] = listaProprietarios.getEmail();
                linha[3] = "+" + fone.getDdi() + fone.getDdd() + fone.getNumero();
                linha[4] = listaProprietarios.getCnh();
                linha[5] = listaProprietarios.getCategoria();
                linha[6] = listaProprietarios.getImagem();

                //linha     
                model.addRow(linha);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }
    private void LimparGrid(){
        model.setNumRows(0);
        
    }
    private void LimparTela(){
        jFormattedTextFieldCpf.setText("");
        jTextFieldNomeCompleto.setText("");
        jTextFieldEmail.setText("");
        jFormattedTextFieldDDI.setText("");
        jFormattedTextFieldDDD.setText("");
        jFormattedTextFieldNumero.setText("");
        jFormattedTextFieldCNH.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNomeCompleto = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButtonAlterarProprietario = new javax.swing.JButton();
        jButtonIncluirAtualizarGrid = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonSelecionarImagem = new javax.swing.JButton();
        jLabel_imagem = new javax.swing.JLabel();
        jFormattedTextFieldDDD = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNumero = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDDI = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jButtonIncluirProprietario = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldCNH = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSaida = new javax.swing.JTable();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1100, 900));

        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 900));

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel4.setText("CPF");

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel5.setText("NOME COMPLETO");

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel6.setText("EMAIL");

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel7.setText("CNH");

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel8.setText("TELEFONE ");

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel9.setText("CATEGORIA ");

        jTextFieldNomeCompleto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jComboBoxCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "AB" }));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exemplocnh.png"))); // NOI18N

        jButtonAlterarProprietario.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButtonAlterarProprietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/escreva.png"))); // NOI18N
        jButtonAlterarProprietario.setText("ALTERAR");
        jButtonAlterarProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarProprietarioActionPerformed(evt);
            }
        });

        jButtonIncluirAtualizarGrid.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButtonIncluirAtualizarGrid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/atualizar.png"))); // NOI18N
        jButtonIncluirAtualizarGrid.setText("ATUALIZAR");
        jButtonIncluirAtualizarGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirAtualizarGridActionPerformed(evt);
            }
        });

        jButtonConsultar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButtonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/procurar.png"))); // NOI18N
        jButtonConsultar.setText("CONSULTAR");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jButtonSelecionarImagem.setText("SELECIONAR");
        jButtonSelecionarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarImagemActionPerformed(evt);
            }
        });

        jLabel_imagem.setBackground(new java.awt.Color(255, 51, 51));
        jLabel_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fotopessoa.png"))); // NOI18N
        jLabel_imagem.setPreferredSize(new java.awt.Dimension(145, 166));

        try {
            jFormattedTextFieldDDD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDDD.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        try {
            jFormattedTextFieldNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNumero.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        try {
            jFormattedTextFieldDDI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDDI.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        try {
            jFormattedTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCpf.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jButtonIncluirProprietario.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButtonIncluirProprietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/adicionar-contato.png"))); // NOI18N
        jButtonIncluirProprietario.setText("INCLUIR");
        jButtonIncluirProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirProprietarioActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel10.setText("     FOTO");

        try {
            jFormattedTextFieldCNH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCNH.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(145, 145, 145))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(4, 4, 4)
                        .addComponent(jButtonIncluirAtualizarGrid, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonIncluirProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterarProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConsultar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextFieldNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel6))
                                            .addGap(12, 12, 12)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jFormattedTextFieldDDI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jFormattedTextFieldDDD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jFormattedTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(192, 192, 192)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jFormattedTextFieldCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(478, 478, 478)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSelecionarImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jFormattedTextFieldDDD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldDDI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jFormattedTextFieldCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSelecionarImagem))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluirAtualizarGrid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIncluirProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterarProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(553, 553, 553))
        );

        jTableSaida.setBackground(new java.awt.Color(255, 255, 153));
        jTableSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "NOME COMPLETO", "EMAIL", "TELEFONE", "CNH", "CATEGORIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSaida.setShowGrid(true);
        jTableSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSaidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSaida);
        if (jTableSaida.getColumnModel().getColumnCount() > 0) {
            jTableSaida.getColumnModel().getColumn(0).setResizable(false);
            jTableSaida.getColumnModel().getColumn(1).setResizable(false);
            jTableSaida.getColumnModel().getColumn(2).setResizable(false);
            jTableSaida.getColumnModel().getColumn(3).setResizable(false);
            jTableSaida.getColumnModel().getColumn(4).setResizable(false);
            jTableSaida.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarProprietarioActionPerformed
        try {

           String cpf = jFormattedTextFieldCpf.getText();
            String nomecompleto = jTextFieldNomeCompleto.getText();
            String email = jTextFieldEmail.getText();

            Telefone fone = new Telefone((jFormattedTextFieldDDI.getText()),
                                         (jFormattedTextFieldDDD.getText()),
                                         (jFormattedTextFieldNumero.getText()));

            String cnh = jFormattedTextFieldCNH.getText();
            String categoria = (String) jComboBoxCategoria.getSelectedItem();

            Proprietario proprietario = new Proprietario(cpf, nomecompleto, email, fone, cnh, categoria, caminho);

            proprietarioControle.Alterar(proprietario);
            
            
            JOptionPane.showMessageDialog(this, "ALTERADO COM SUCESSO");
            mostrarDados();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
            
        }
    }//GEN-LAST:event_jButtonAlterarProprietarioActionPerformed

    private void jButtonIncluirAtualizarGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirAtualizarGridActionPerformed
        // TODO add your handling code here:
        mostrarDados();

    }//GEN-LAST:event_jButtonIncluirAtualizarGridActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        try {
            LimparGrid();
            Proprietario proprietario = proprietarioControle.Consultar(jFormattedTextFieldCpf.getText());
            Telefone fone = null;
            fone = proprietario.getFone();
            DefaultTableModel model = (DefaultTableModel) jTableSaida.getModel();

            String[] linha = new String[7];
            linha[0] = proprietario.getCpf();
            linha[1] = proprietario.getNomecompleto();
            linha[2] = proprietario.getEmail();
            linha[3] = "" + fone.getDdi() + fone.getDdd() + fone.getNumero();
            linha[4] = proprietario.getCnh();
            linha[5] = proprietario.getCategoria();

            model.addRow(linha);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonSelecionarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarImagemActionPerformed
        // TODO add your handling code here:
        try {

            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            caminho = f.getAbsolutePath();
            BufferedImage bi = ImageIO.read(new File(caminho));
            Image img = bi.getScaledInstance(131, 166, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            jLabel_imagem.setIcon(icon);
        } catch (IOException ex) {
            // Logger.getLogger(TelaDeCadastroDeProprietarios.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonSelecionarImagemActionPerformed

    private void jButtonIncluirProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirProprietarioActionPerformed
        // TODO add your handling code here:
        try {

            String cpf = jFormattedTextFieldCpf.getText();
            String nomecompleto = jTextFieldNomeCompleto.getText();
            String email = jTextFieldEmail.getText();

            Telefone fone = new Telefone((jFormattedTextFieldDDI.getText()),
                                         (jFormattedTextFieldDDD.getText()),
                                         (jFormattedTextFieldNumero.getText()));

            String cnh = jFormattedTextFieldCNH.getText();
            String categoria = (String) jComboBoxCategoria.getSelectedItem();

            Proprietario proprietario = new Proprietario(cpf, nomecompleto, email, fone, cnh, categoria, caminho);

            proprietarioControle.Incluir(proprietario);

            mostrarDados();

            JOptionPane.showMessageDialog(this, "INCLUIDO COM SUCESSO");
            LimparTela();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirProprietarioActionPerformed

    private void jTableSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSaidaMouseClicked
        // TODO add your handling code here:
        try {

            int numeroLinha = jTableSaida.getSelectedRow();
            String telefone = jTableSaida.getValueAt(numeroLinha, 3).toString();
            String ddi = telefone.substring(0, 3);
            String ddd = telefone.substring(3, 5);
            String numeroTelefone = telefone.substring(5);

            jFormattedTextFieldDDI.setText(ddi);
            jFormattedTextFieldDDD.setText(ddd);
            jFormattedTextFieldNumero.setText(numeroTelefone);
            Proprietario proprietario = new Proprietario();

            ArrayList<Proprietario> ObterListagemDeContatos = null;
            ObterListagemDeContatos = proprietarioControle.ObterListagemDeContatos();
            Proprietario i = ObterListagemDeContatos.get(numeroLinha);

            jFormattedTextFieldCpf.setText("" + i.getCpf());
            jTextFieldNomeCompleto.setText("" + i.getNomecompleto());
            jTextFieldEmail.setText("" + i.getEmail());
            jFormattedTextFieldCNH.setText("" + i.getCnh());

            caminho = "" + i.getImagem();
            System.out.println(jTableSaida);
            BufferedImage bi = ImageIO.read(new File(caminho));
            Image img = bi.getScaledInstance(131, 166, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            jLabel_imagem.setIcon(icon);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jTableSaidaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarProprietario;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonIncluirAtualizarGrid;
    private javax.swing.JButton jButtonIncluirProprietario;
    private javax.swing.JButton jButtonSelecionarImagem;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNH;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldDDD;
    private javax.swing.JFormattedTextField jFormattedTextFieldDDI;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumero;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_imagem;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSaida;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNomeCompleto;
    // End of variables declaration//GEN-END:variables
}
