/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visao;
import controle.MarcaControle;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import modelos.Marca;
import modelos.IMarcaCRUD;
import modelos.MarcasEnum;


public class TelaCadastroMarcas extends javax.swing.JInternalFrame {

      IMarcaCRUD marcaControle = null;
      String logo = "";
      
    public TelaCadastroMarcas() {
        initComponents();
          marcaControle = new MarcaControle();
           this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);       
          mostrarDados();
          

    }
    private void mostrarDados(){
    try {
      ArrayList<Marca> listaDeMarcas = null;
      listaDeMarcas = marcaControle.ObterListagemDeMarcas();
      DefaultTableModel model =  (DefaultTableModel) jTableSaidaMarca.getModel();
      model.setNumRows(0);
      if(listaDeMarcas.isEmpty()) return;
      for(int pos = 0; pos < listaDeMarcas.size(); pos++){
      Marca listaMarcas = listaDeMarcas.get(pos);
         
     
        
        String[] linha = new String[3];
        
        linha[0]= listaMarcas.getId();
        linha[1]= listaMarcas.getMarca();
        linha[2] = listaMarcas.getLogo();        
          
        
        
        //linha     
        model.addRow(linha);
      }
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, erro.getMessage());
    }
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSaidaMarca = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIdDaMarca = new javax.swing.JTextField();
        jButtonAlterarMarcas = new javax.swing.JButton();
        jButtonIncluirModelo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogoDaMarca = new javax.swing.JLabel();
        jButtonSelecionarLogoMarca = new javax.swing.JButton();
        jComboBoxMarcaVeiculo = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(1100, 900));
        setPreferredSize(new java.awt.Dimension(1100, 900));

        jTableSaidaMarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "MARCA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSaidaMarca.setMaximumSize(new java.awt.Dimension(900, 800));
        jTableSaidaMarca.setMinimumSize(new java.awt.Dimension(900, 800));
        jTableSaidaMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSaidaMarcaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSaidaMarca);
        if (jTableSaidaMarca.getColumnModel().getColumnCount() > 0) {
            jTableSaidaMarca.getColumnModel().getColumn(0).setResizable(false);
            jTableSaidaMarca.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel7.setText("Marca");

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel4.setText("ID");

        jTextFieldIdDaMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonAlterarMarcas.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButtonAlterarMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/escreva.png"))); // NOI18N
        jButtonAlterarMarcas.setText("ALTERAR");
        jButtonAlterarMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarMarcasActionPerformed(evt);
            }
        });

        jButtonIncluirModelo.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButtonIncluirModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/adicionar-contato.png"))); // NOI18N
        jButtonIncluirModelo.setText("INCLUIR");
        jButtonIncluirModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirModeloActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setText("marca do veiculo");

        jButtonSelecionarLogoMarca.setText("SELECIONAR LOGO");
        jButtonSelecionarLogoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarLogoMarcaActionPerformed(evt);
            }
        });

        jComboBoxMarcaVeiculo.setModel(new DefaultComboBoxModel(MarcasEnum.values()));
        jComboBoxMarcaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarcaVeiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jButtonIncluirModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(49, 49, 49)
                                .addComponent(jTextFieldIdDaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlterarMarcas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27)
                        .addComponent(jComboBoxMarcaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLogoDaMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jButtonSelecionarLogoMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(303, 303, 303))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldIdDaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxMarcaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonIncluirModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAlterarMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jLabelLogoDaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSelecionarLogoMarca)
                        .addGap(70, 70, 70))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIncluirModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirModeloActionPerformed
        // TODO add your handling code here:
        try {
            
            String id = jTextFieldIdDaMarca.getText();
            String marca = jComboBoxMarcaVeiculo.getSelectedItem().toString();
            
            
            
            Marca marcas = new Marca(id, marca, logo);

            marcaControle.Incluir(marcas);
            
            mostrarDados();
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirModeloActionPerformed

    private void jTableSaidaMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSaidaMarcaMouseClicked
        
        try {
            int numeroLinha = jTableSaidaMarca.getSelectedRow();
            
            ArrayList<Marca> ObterListagemDeMarcas = null;
            ObterListagemDeMarcas = marcaControle.ObterListagemDeMarcas();
            Marca i = ObterListagemDeMarcas.get(numeroLinha);

            jTextFieldIdDaMarca.setText(""+i.getId());
            //jComboBoxMarcaVeiculo.set(""+i.getMarca());
            
            
            logo = ""+i.getLogo();
            
            BufferedImage bi = ImageIO.read(new File(logo) );
            Image img = bi.getScaledInstance(131, 166,Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            jLabelLogoDaMarca.setIcon(icon);

        } catch (Exception erro) {

            JOptionPane.showMessageDialog(null, erro.getMessage());
        }

    }//GEN-LAST:event_jTableSaidaMarcaMouseClicked

    private void jButtonSelecionarLogoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarLogoMarcaActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            logo = f.getAbsolutePath();
            BufferedImage bi = ImageIO.read(new File(logo) );
            Image img = bi.getScaledInstance(131, 166,Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            jLabelLogoDaMarca.setIcon(icon);
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }

            
        
        
        
    }//GEN-LAST:event_jButtonSelecionarLogoMarcaActionPerformed

    private void jButtonAlterarMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarMarcasActionPerformed
        // TODO add your handling code here:
        try {
            
            String id = jTextFieldIdDaMarca.getText();
            String marca = jComboBoxMarcaVeiculo.getSelectedItem().toString();
            
            
            
            
            Marca marcas = new Marca(id, marca, logo);

            marcaControle.Alterar(marcas);
            mostrarDados();
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
            
           
        
        
        
    }//GEN-LAST:event_jButtonAlterarMarcasActionPerformed

    private void jComboBoxMarcaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarcaVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMarcaVeiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarMarcas;
    private javax.swing.JButton jButtonIncluirModelo;
    private javax.swing.JButton jButtonSelecionarLogoMarca;
    private javax.swing.JComboBox<String> jComboBoxMarcaVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelLogoDaMarca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSaidaMarca;
    private javax.swing.JTextField jTextFieldIdDaMarca;
    // End of variables declaration//GEN-END:variables

   
}
