/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visao;

import controle.ModeloControle;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import modelos.IModeloCRUD;
import modelos.Modelo;
import java.util.ArrayList;
import modelos.Marca;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author pcgamergab
 */
public class TelaCadastroModelo extends javax.swing.JInternalFrame {
     IModeloCRUD modeloControle = null;
    ArrayList<Marca> ObterListagemDeMarcas = null;
    private String nomeDoArquivoNoDisco = null;
    
    
    public TelaCadastroModelo() {
        initComponents();
        nomeDoArquivoNoDisco = "./src/bancodedados/Marcabd.txt";
        try {
            ComboBox();
            
        } catch (Exception e) {
        }
        
     
       
     
         
        modeloControle = new ModeloControle();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);  
        mostrarDados();
     
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSaida = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFielDescrição = new javax.swing.JTextField();
        jTextFieldIDMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonIncluirModelo = new javax.swing.JButton();
        jButtonAlterarModelo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxTipoDoVeiculo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxMarcas = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(1100, 900));
        setPreferredSize(new java.awt.Dimension(1100, 900));

        jTableSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Marca", "DESCRIÇÃO", "Tipo do veiculo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSaida.setMaximumSize(new java.awt.Dimension(900, 800));
        jTableSaida.setMinimumSize(new java.awt.Dimension(900, 800));
        jTableSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSaidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSaida);
        if (jTableSaida.getColumnModel().getColumnCount() > 0) {
            jTableSaida.getColumnModel().getColumn(0).setResizable(false);
            jTableSaida.getColumnModel().getColumn(1).setResizable(false);
            jTableSaida.getColumnModel().getColumn(2).setResizable(false);
            jTableSaida.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel7.setText("Descrição");

        jTextFielDescrição.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldIDMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Modelo do veiculo");

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel6.setText("ID");

        jButtonIncluirModelo.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButtonIncluirModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/adicionar-contato.png"))); // NOI18N
        jButtonIncluirModelo.setText("INCLUIR");
        jButtonIncluirModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirModeloActionPerformed(evt);
            }
        });

        jButtonAlterarModelo.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButtonAlterarModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/escreva.png"))); // NOI18N
        jButtonAlterarModelo.setText("ALTERAR");
        jButtonAlterarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarModeloActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel9.setText("Marca");

        jComboBoxTipoDoVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEDAN", "HATCH", "SUV", "UTILITARIO" }));
        jComboBoxTipoDoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDoVeiculoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel10.setText("Tipo do veiculo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonIncluirModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAlterarModelo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFielDescrição, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldIDMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBoxMarcas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxTipoDoVeiculo, javax.swing.GroupLayout.Alignment.LEADING, 0, 118, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addContainerGap(494, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIDMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jTextFielDescrição, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxTipoDoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluirModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void mostrarDados(){
    try {
      ArrayList<Modelo> listaDeModelos = null;
      listaDeModelos = modeloControle.ObterListagemDeModelos();
      DefaultTableModel model =  (DefaultTableModel) jTableSaida.getModel();
      model.setNumRows(0);
      if(listaDeModelos.isEmpty()) return;
      for(int pos = 0; pos < listaDeModelos.size(); pos++){
      Modelo listaModelos = listaDeModelos.get(pos);
         
     
        
        String[] linha = new String[4];
        
        linha[0]= listaModelos.getId();
        linha[1]= listaModelos.getMarca();
        linha[2]= listaModelos.getDescricao();        
        linha[3]= listaModelos.getTipoDoVeiculo();  
        
        //linha     
        model.addRow(linha);
      }
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, erro.getMessage());
    }
  }
    public void ComboBox() throws Exception {
        try {
            FileReader fr = new FileReader(nomeDoArquivoNoDisco);
            BufferedReader br = new BufferedReader(fr);
            String linha = "";
            while ((linha = br.readLine()) != null) {
                String vetorStr[] = linha.split(";");
                String descricao = vetorStr[1];              
                jComboBoxMarcas.addItem(descricao);
            }
            br.close();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage(), "Método comboBox", JOptionPane.ERROR_MESSAGE);
        }

    }
 
    private void jButtonIncluirModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirModeloActionPerformed
        // TODO add your handling code here:
        try {
            String id =   jTextFieldIDMarca.getText();
            String descricao = jTextFielDescrição.getText();
            String marca = (String) jComboBoxMarcas.getSelectedItem();
            String tipoDoVeiculo = (String) jComboBoxTipoDoVeiculo.getSelectedItem();
            
                    
               
               
                     

                    
            Modelo modelos = new Modelo(id, descricao, marca, tipoDoVeiculo);
            modeloControle.Incluir(modelos);
            mostrarDados();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirModeloActionPerformed

    private void jTableSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSaidaMouseClicked
        // TODO add your handling code here:
         try {
            int numeroLinha = jTableSaida.getSelectedRow();
            
            ArrayList<Modelo> ObterListagemDeModelos = null;
            ObterListagemDeModelos = modeloControle.ObterListagemDeModelos();
            Modelo i = ObterListagemDeModelos.get(numeroLinha);

            jTextFieldIDMarca.setText(""+i.getId());
            jTextFielDescrição.setText(""+i.getDescricao());
            
            
         
            
            

        } catch (Exception erro) {

            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jTableSaidaMouseClicked

    private void jButtonAlterarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarModeloActionPerformed

    private void jComboBoxTipoDoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDoVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoDoVeiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarModelo;
    private javax.swing.JButton jButtonIncluirModelo;
    private javax.swing.JComboBox<String> jComboBoxMarcas;
    private javax.swing.JComboBox<String> jComboBoxTipoDoVeiculo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSaida;
    private javax.swing.JTextField jTextFielDescrição;
    private javax.swing.JTextField jTextFieldIDMarca;
    // End of variables declaration//GEN-END:variables
}
