/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visao;
import modelos.Veiculo;
import controle.VeiculoControle;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import modelos.IVeiculoCRUD;


/**
 *
 * @author Aluno
 */
public class TelaDeVeiculo extends javax.swing.JInternalFrame {
    IVeiculoCRUD veiculoControle = null;
    DefaultTableModel model;
    String nomeDoArquivoNoDisco = null;
    String nomeDoArquivoNoDiscop = null;
    String logo = "";
    
    public TelaDeVeiculo() {
        initComponents();
        veiculoControle = new VeiculoControle();
        nomeDoArquivoNoDisco = "./src/bancodedados/Modelobd.txt";
        nomeDoArquivoNoDiscop = "./src/bancodedados/Proprietariosbd.txt";
        try {
            mostrarDados();
            ComboBox();
            ComboBoxProprietario();
       
        model = (DefaultTableModel) jTableCadastroDeVeiculo.getModel();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);   

        } catch (Exception e) {
        }
    }
private void mostrarDados(){
    try {
      ArrayList<Veiculo> listaDeVeiculos = null;
      listaDeVeiculos = veiculoControle.ObterListagemDeVeiculos();
      DefaultTableModel model =  (DefaultTableModel) jTableCadastroDeVeiculo.getModel();
      model.setNumRows(0);
      if(listaDeVeiculos.isEmpty()) return;
      for(int pos = 0; pos < listaDeVeiculos.size(); pos++){
      Veiculo listaVeiculos = listaDeVeiculos.get(pos);
         
     
        
        String[] linha = new String[6];
        
        linha[0]= listaVeiculos.getPlaca();
        linha[1]= listaVeiculos.getCor();
        linha[2]= listaVeiculos.getCombustivel();        
        linha[3]= listaVeiculos.getModelo();
        linha[4]= listaVeiculos.getAno();
        linha[5]= listaVeiculos.getProprietarioVeiculo();
        
        //linha     
        model.addRow(linha);
      }
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, erro.getMessage());
    }
  }
public void ComboBox() throws Exception {
        try {
            FileReader fr = new FileReader(nomeDoArquivoNoDisco);
            BufferedReader br = new BufferedReader(fr);
            String linha = "";
            while ((linha = br.readLine()) != null) {
                String vetorStr[] = linha.split(";");
                String descricao = vetorStr[1];              
                jComboBoxModelo.addItem(descricao);
            }
            br.close();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage(), "Método comboBox TelaDeVeiculo", JOptionPane.ERROR_MESSAGE);
        }
}
        public void ComboBoxProprietario() throws Exception {
        try {
            FileReader fr = new FileReader(nomeDoArquivoNoDiscop);
            BufferedReader br = new BufferedReader(fr);
            String linha = "";
            while ((linha = br.readLine()) != null) {
                String vetorStr[] = linha.split(";");
                String descricao = vetorStr[1];              
                jComboBoxProprietarioVeiculo.addItem(descricao);
            }
            br.close();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage(), "Método comboBox", JOptionPane.ERROR_MESSAGE);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFielAno = new javax.swing.JTextField();
        jTextFielCor = new javax.swing.JTextField();
        jComboBoxCombustivelCadastroVeiculo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastroDeVeiculo = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxModelo = new javax.swing.JComboBox<>();
        jButtonCadastrarVeiculo = new javax.swing.JButton();
        jButtonAlterarCadastroDeVeiculo = new javax.swing.JButton();
        jLabelLogoDaMarca = new javax.swing.JLabel();
        jButtonSelecionarCarro = new javax.swing.JButton();
        jLabelCadastroVeiculo1 = new javax.swing.JLabel();
        jFormattedTextFieldPlaca = new javax.swing.JFormattedTextField();
        jComboBoxProprietarioVeiculo = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 900));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel5.setText("cadastro do veículo");

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel6.setText("PLACA");

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel7.setText("COMBUSTIVEL");

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel8.setText("ANO");

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel9.setText("COR");

        jInternalFrame1.setPreferredSize(new java.awt.Dimension(1100, 900));

        jLabel10.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel10.setText("cadastro do veículo");

        jLabel13.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel13.setText("PLACA");

        jLabel14.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel14.setText("COMBUSTIVEL");

        jLabel15.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel15.setText("ANO");

        jLabel16.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel16.setText("COR");

        jLabel17.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel18.setText("TIPO DO VEÍCULO");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(173, 173, 173)
                                .addComponent(jLabel15))
                            .addComponent(jLabel14)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addGap(65, 65, 65)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addGap(33, 33, 33)
                .addComponent(jLabel16)
                .addGap(36, 36, 36)
                .addComponent(jLabel14)
                .addGap(36, 36, 36)
                .addComponent(jLabel18)
                .addGap(46, 46, 46)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextFielAno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFielCor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jComboBoxCombustivelCadastroVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GASOLINA COMUM", "GASOLINA ADTIVADA", "GASOLINA_PREMIUM", "DIESEL", "DIESEL_COMUM_S500", "DIESEL_S10", "DIESEL_ADTIVADO", "DIESEL_PREMIUM", "ETANOL_COMUM", "ETANOL_ADTIVADO", "GAS NATURAL GNV" }));
        jComboBoxCombustivelCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCombustivelCadastroVeiculoActionPerformed(evt);
            }
        });

        jTableCadastroDeVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PLACA", "COR", "COMBUSTIVEL", "MODELO", "ANO", "PROPRIETARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCadastroDeVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCadastroDeVeiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCadastroDeVeiculo);
        if (jTableCadastroDeVeiculo.getColumnModel().getColumnCount() > 0) {
            jTableCadastroDeVeiculo.getColumnModel().getColumn(0).setResizable(false);
            jTableCadastroDeVeiculo.getColumnModel().getColumn(1).setResizable(false);
            jTableCadastroDeVeiculo.getColumnModel().getColumn(2).setResizable(false);
            jTableCadastroDeVeiculo.getColumnModel().getColumn(3).setResizable(false);
            jTableCadastroDeVeiculo.getColumnModel().getColumn(4).setResizable(false);
            jTableCadastroDeVeiculo.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel19.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel19.setText("MODELO");

        jButtonCadastrarVeiculo.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButtonCadastrarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/carrogastos.png"))); // NOI18N
        jButtonCadastrarVeiculo.setText("CADASTRAR");
        jButtonCadastrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarVeiculoActionPerformed(evt);
            }
        });

        jButtonAlterarCadastroDeVeiculo.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButtonAlterarCadastroDeVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/escreva.png"))); // NOI18N
        jButtonAlterarCadastroDeVeiculo.setText("ALTERAR");
        jButtonAlterarCadastroDeVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarCadastroDeVeiculoActionPerformed(evt);
            }
        });

        jButtonSelecionarCarro.setText("SELECIONAR CARRO");
        jButtonSelecionarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarCarroActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-#A##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel24.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel24.setText("VEICULOS ");

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel11.setText("PROPRIETARIO VEICULO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFielCor, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldPlaca))
                        .addGap(56, 56, 56)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFielAno, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLogoDaMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxProprietarioVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxCombustivelCadastroVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jButtonCadastrarVeiculo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonAlterarCadastroDeVeiculo)
                                            .addComponent(jComboBoxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(533, 533, 533)
                                .addComponent(jButtonSelecionarCarro))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(314, 314, 314)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(898, 898, 898)
                    .addComponent(jLabelCadastroVeiculo1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addGap(47, 47, 47)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel24)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabelLogoDaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComboBoxProprietarioVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155)))
                        .addComponent(jButtonSelecionarCarro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(jTextFielAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFielCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxCombustivelCadastroVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jComboBoxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCadastrarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAlterarCadastroDeVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(jLabelCadastroVeiculo1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(612, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel24)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarVeiculoActionPerformed
        try {
            String placa = jFormattedTextFieldPlaca.getText();
            String cor = jTextFielCor.getText();
            String combustivel = (String)jComboBoxCombustivelCadastroVeiculo.getSelectedItem(). toString();
            String modelo = (String) jComboBoxModelo.getSelectedItem();
            String ano = jTextFielAno.getText();
            String proprietarioVeiculo = (String) jComboBoxProprietarioVeiculo.getSelectedItem();
            Veiculo veiculo = new Veiculo(placa, cor, combustivel, modelo, ano, proprietarioVeiculo);
            
            veiculoControle.Cadastrar(veiculo);
            mostrarDados();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
 

    }//GEN-LAST:event_jButtonCadastrarVeiculoActionPerformed

    private void jButtonAlterarCadastroDeVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarCadastroDeVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarCadastroDeVeiculoActionPerformed

    private void jTableCadastroDeVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCadastroDeVeiculoMouseClicked
         /** try {
            int numeroLinha = jTableCadastroDeVeiculo.getSelectedRow();
            
            ArrayList<Veiculo> ObterListagemDeVeiculos = null;
            ObterListagemDeVeiculos = veiculoControle.ObterListagemDeVeiculos();
            Veiculo i = ObterListagemDeVeiculos.get(numeroLinha);

            jTextFielPlaca.setText(""+i.getPlaca());
            jTextFielCor.setText(""+i.getCor());
            
            
            
            logo = ""+i.getLogo();
            
            BufferedImage bi = ImageIO.read(new File(logo) );
            Image img = bi.getScaledInstance(131, 166,Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            jLabelLogoDaMarca.setIcon(icon);

        } catch (Exception erro) {

            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
        **/
    }//GEN-LAST:event_jTableCadastroDeVeiculoMouseClicked

    private void jButtonSelecionarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarCarroActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            logo = f.getAbsolutePath();
            BufferedImage bi = ImageIO.read(new File(logo) );
            Image img = bi.getScaledInstance(131, 166,Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            jLabelLogoDaMarca.setIcon(icon);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }

    }//GEN-LAST:event_jButtonSelecionarCarroActionPerformed

    private void jComboBoxCombustivelCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCombustivelCadastroVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCombustivelCadastroVeiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarCadastroDeVeiculo;
    private javax.swing.JButton jButtonCadastrarVeiculo;
    private javax.swing.JButton jButtonSelecionarCarro;
    private javax.swing.JComboBox<String> jComboBoxCombustivelCadastroVeiculo;
    private javax.swing.JComboBox<String> jComboBoxModelo;
    private javax.swing.JComboBox<String> jComboBoxProprietarioVeiculo;
    private javax.swing.JFormattedTextField jFormattedTextFieldPlaca;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCadastroVeiculo1;
    private javax.swing.JLabel jLabelLogoDaMarca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadastroDeVeiculo;
    private javax.swing.JTextField jTextFielAno;
    private javax.swing.JTextField jTextFielCor;
    // End of variables declaration//GEN-END:variables
}
