/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visao;

import controle.TiposDeGastosControle;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import modelos.ITiposDeGastosCRUD;
import modelos.TiposDeGastos;

/**
 *
 * @author Aluno
 */
public class TelaGastos extends javax.swing.JInternalFrame {
    
    private String nomeDoArquivoNoDiscov = null;
    ITiposDeGastosCRUD tipodegastoscontrole = null;
    String modeloVeiculo = null;
   

    public TelaGastos() {
        initComponents();      
        tipodegastoscontrole = new TiposDeGastosControle();       
        nomeDoArquivoNoDiscov = "./src/bancodedados/Veiculobd.txt";
        mostrarDados();
        
        try {
            ComboBox();
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
        

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

    }

    public void ComboBox() throws Exception {
        try {
            FileReader fr = new FileReader(nomeDoArquivoNoDiscov);
            BufferedReader br = new BufferedReader(fr);
            String linha = "";
            while ((linha = br.readLine()) != null) {
                String vetorStr[] = linha.split(";");
                String descricao = vetorStr[5];
                jComboBoxPlaca.addItem(descricao);
            }
            br.close();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage(), "Método comboBox", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void mostrarDados() {
        try {
            ArrayList<TiposDeGastos> listaDeGastos = null;
            listaDeGastos = tipodegastoscontrole.ObterListagemDeTiposDeGastos();
            DefaultTableModel model = (DefaultTableModel) jTableSaidaGastos.getModel();
            model.setNumRows(0);
            if (listaDeGastos.isEmpty()) {
                return;
            }
            for (int pos = 0; pos < listaDeGastos.size(); pos++) {
                TiposDeGastos listaGastos = listaDeGastos.get(pos);

                String[] linha = new String[4];

                linha[0] = listaGastos.getTipodogastos();
                linha[1] = listaGastos.getValor();
                linha[2] = listaGastos.getData();
                linha[3] = listaGastos.getPlaca();
                
                //linha     
                model.addRow(linha);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxCombustivel = new javax.swing.JComboBox<>();
        jComboBoxManutenção1 = new javax.swing.JComboBox<>();
        jComboBoxPedagio = new javax.swing.JComboBox<>();
        jComboBoxIpva = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxSeguro = new javax.swing.JComboBox<>();
        jFormattedTextFieldDataDosGastos = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldValorDaManutencao = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldValorDoCombustivel = new javax.swing.JTextField();
        jTextFieldValorDoIpva = new javax.swing.JTextField();
        jTextFieldValorDoSeguro = new javax.swing.JTextField();
        jTextFieldValorDoPedagio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSaidaGastos = new javax.swing.JTable();
        jButtonAdicionarManutencao = new javax.swing.JButton();
        jButtonAdicionarCombustivel = new javax.swing.JButton();
        jButtonAdicionarIpva = new javax.swing.JButton();
        jButtonAdicionarPedagio = new javax.swing.JButton();
        jButtonAdicionarSeguro = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jComboBoxPlaca = new javax.swing.JComboBox<>();
        jComboBoxVeiculos = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 900));
        setPreferredSize(new java.awt.Dimension(1280, 900));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setText("GASTOS DO PROPRIETARIO");

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel7.setText("MANUTENÇÃO");

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel8.setText("COMBUSTIVEL");

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel9.setText("IPVA");

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel10.setText("PEDAGIO");

        jComboBoxCombustivel.setModel(new DefaultComboBoxModel(modelos.TiposDeGastosEnum.Combustivel.values())
        );
        jComboBoxCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCombustivelActionPerformed(evt);
            }
        });

        jComboBoxManutenção1.setModel(new DefaultComboBoxModel(modelos.TiposDeGastosEnum.Manutencao.values()));
        jComboBoxManutenção1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxManutenção1ActionPerformed(evt);
            }
        });

        jComboBoxPedagio.setModel(new  DefaultComboBoxModel(modelos.TiposDeGastosEnum.Pedagio.values())
        );
        jComboBoxPedagio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPedagioActionPerformed(evt);
            }
        });

        jComboBoxIpva.setModel(new DefaultComboBoxModel(modelos.TiposDeGastosEnum.IPVA.values())
        );
        jComboBoxIpva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIpvaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel11.setText("SEGURO");

        jComboBoxSeguro.setModel(new DefaultComboBoxModel(modelos.TiposDeGastosEnum.Seguro.values())
        );
        jComboBoxSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSeguroActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldDataDosGastos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataDosGastos.setText("");
        jFormattedTextFieldDataDosGastos.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jLabel13.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel13.setText("VALOR");

        jTextFieldValorDaManutencao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel18.setText("VALOR");

        jLabel19.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel19.setText("VALOR");

        jLabel20.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel20.setText("VALOR");

        jLabel21.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel21.setText("VALOR");

        jLabel22.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel22.setText("DATA DOS GASTOS");

        jTextFieldValorDoCombustivel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldValorDoIpva.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldValorDoSeguro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldValorDoPedagio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTableSaidaGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TIPO DE GASTOS", "VALOR", "DATA", "PLACA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableSaidaGastos);

        jButtonAdicionarManutencao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAdicionarManutencao.setText("ADICIONAR");
        jButtonAdicionarManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarManutencaoActionPerformed(evt);
            }
        });

        jButtonAdicionarCombustivel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAdicionarCombustivel.setText("ADICIONAR");
        jButtonAdicionarCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarCombustivelActionPerformed(evt);
            }
        });

        jButtonAdicionarIpva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAdicionarIpva.setText("ADICIONAR");
        jButtonAdicionarIpva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarIpvaActionPerformed(evt);
            }
        });

        jButtonAdicionarPedagio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAdicionarPedagio.setText("ADICIONAR");
        jButtonAdicionarPedagio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarPedagioActionPerformed(evt);
            }
        });

        jButtonAdicionarSeguro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAdicionarSeguro.setText("ADICIONAR");
        jButtonAdicionarSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarSeguroActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel23.setText("PROPRIETARIO");

        jComboBoxPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlacaActionPerformed(evt);
            }
        });

        jComboBoxVeiculos.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel24.setText("PLACAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxManutenção1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxIpva, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxPedagio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldValorDoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldValorDoPedagio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldValorDoIpva, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldValorDoCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(jTextFieldValorDaManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonAdicionarManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAdicionarCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAdicionarIpva, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAdicionarPedagio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAdicionarSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(104, 104, 104)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFormattedTextFieldDataDosGastos, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(jComboBoxPlaca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(51, 51, 51)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(403, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldDataDosGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jComboBoxVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jComboBoxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxManutenção1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldValorDaManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarManutencao))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldValorDoCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarCombustivel))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxIpva, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldValorDoIpva, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarIpva))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPedagio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldValorDoPedagio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarPedagio))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldValorDoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarSeguro))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCombustivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCombustivelActionPerformed

    private void jComboBoxManutenção1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxManutenção1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxManutenção1ActionPerformed

    private void jComboBoxPedagioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPedagioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPedagioActionPerformed

    private void jComboBoxIpvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIpvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIpvaActionPerformed

    private void jComboBoxSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSeguroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSeguroActionPerformed

    private void jButtonAdicionarManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarManutencaoActionPerformed
        try {
            String manutencao = jComboBoxManutenção1.getSelectedItem().toString();
            String valor = jTextFieldValorDaManutencao.getText();
            String data = jFormattedTextFieldDataDosGastos.getText();
            String placa = (String)jComboBoxVeiculos.getSelectedItem();
            TiposDeGastos gastos = new TiposDeGastos(manutencao, valor, data, placa);

            tipodegastoscontrole.Incluir(gastos);

            mostrarDados();

            jTextFieldValorDaManutencao.setText("");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());

        }
    }//GEN-LAST:event_jButtonAdicionarManutencaoActionPerformed

    private void jButtonAdicionarCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarCombustivelActionPerformed
        try {
            String manutencao = jComboBoxCombustivel.getSelectedItem().toString();
            String valor = jTextFieldValorDoCombustivel.getText();
            String data = jFormattedTextFieldDataDosGastos.getText();
            String placa = (String)jComboBoxPlaca.getSelectedItem();     
            TiposDeGastos gastos = new TiposDeGastos(manutencao, valor, data, placa);

            tipodegastoscontrole.Incluir(gastos);

            mostrarDados();

            jTextFieldValorDoCombustivel.setText("");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());

        }
    }//GEN-LAST:event_jButtonAdicionarCombustivelActionPerformed

    private void jButtonAdicionarIpvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarIpvaActionPerformed
        try {
            String manutencao = jComboBoxIpva.getSelectedItem().toString();
            String valor = jTextFieldValorDoIpva.getText();
            String data = jFormattedTextFieldDataDosGastos.getText();
            String placa = (String)jComboBoxPlaca.getSelectedItem();
            TiposDeGastos gastos = new TiposDeGastos(manutencao, valor, data, placa);

            tipodegastoscontrole.Incluir(gastos);

            mostrarDados();

            jTextFieldValorDoIpva.setText("");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());

        }
    }//GEN-LAST:event_jButtonAdicionarIpvaActionPerformed

    private void jButtonAdicionarPedagioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarPedagioActionPerformed
        try {
            String manutencao = jComboBoxPedagio.getSelectedItem().toString();
            String valor = jTextFieldValorDoPedagio.getText();
            String data = jFormattedTextFieldDataDosGastos.getText();
            String placa = (String)jComboBoxPlaca.getSelectedItem();
            TiposDeGastos gastos = new TiposDeGastos(manutencao, valor, data, placa);

            tipodegastoscontrole.Incluir(gastos);

            mostrarDados();

            jTextFieldValorDoPedagio.setText("");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());

        }
    }//GEN-LAST:event_jButtonAdicionarPedagioActionPerformed

    private void jButtonAdicionarSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarSeguroActionPerformed
        try {
            String manutencao = jComboBoxSeguro.getSelectedItem().toString();
            String valor = jTextFieldValorDoSeguro.getText();
            String data = jFormattedTextFieldDataDosGastos.getText();
            String placa = (String)jComboBoxPlaca.getSelectedItem();
            TiposDeGastos gastos = new TiposDeGastos(manutencao, valor, data, placa);

            tipodegastoscontrole.Incluir(gastos);

            mostrarDados();

            jTextFieldValorDoSeguro.setText("");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());

        }
    }//GEN-LAST:event_jButtonAdicionarSeguroActionPerformed

    public void AtualizarComboBoxVeiculos() throws Exception {
              try {
            FileReader fr = new FileReader(nomeDoArquivoNoDiscov);
            BufferedReader br = new BufferedReader(fr);
            String linha = "";
            while ((linha = br.readLine()) != null) {
                String vetorStr[] = linha.split(";");
                if (vetorStr[5].equals
                    (modeloVeiculo)){
                    String descricao = vetorStr[0];
                    jComboBoxVeiculos.addItem(descricao);
                                   }
                            }
            br.close();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage(), "Método comboBox", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void jComboBoxPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlacaActionPerformed
        modeloVeiculo = (String) jComboBoxPlaca.getSelectedItem();
        System.out.println("" + modeloVeiculo);
        try {
            jComboBoxVeiculos.removeAllItems();
            AtualizarComboBoxVeiculos();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }

    }//GEN-LAST:event_jComboBoxPlacaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarCombustivel;
    private javax.swing.JButton jButtonAdicionarIpva;
    private javax.swing.JButton jButtonAdicionarManutencao;
    private javax.swing.JButton jButtonAdicionarPedagio;
    private javax.swing.JButton jButtonAdicionarSeguro;
    private javax.swing.JComboBox<String> jComboBoxCombustivel;
    private javax.swing.JComboBox<String> jComboBoxIpva;
    private javax.swing.JComboBox<String> jComboBoxManutenção1;
    private javax.swing.JComboBox<String> jComboBoxPedagio;
    private javax.swing.JComboBox<String> jComboBoxPlaca;
    private javax.swing.JComboBox<String> jComboBoxSeguro;
    private javax.swing.JComboBox<String> jComboBoxVeiculos;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataDosGastos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSaidaGastos;
    private javax.swing.JTextField jTextFieldValorDaManutencao;
    private javax.swing.JTextField jTextFieldValorDoCombustivel;
    private javax.swing.JTextField jTextFieldValorDoIpva;
    private javax.swing.JTextField jTextFieldValorDoPedagio;
    private javax.swing.JTextField jTextFieldValorDoSeguro;
    // End of variables declaration//GEN-END:variables
}
